### ISSUE TITLE
Why is the camera view also draged?

### ISSUE THREAD

**Issue by syguan96** [showlab/DragAnything#16]
Hi @weijiawu, thanks for releasing the training and test code.  

I tested some images, but I found that not only are the objects moving, but the camera's view is also moving. I want to know if I made a mistake in something?

![vis_gif (1)](https://github.com/showlab/DragAnything/assets/81640539/f31dd20d-b4ca-4490-a7fa-aa2266e19ceb)

**Comment by syguan96** [comment]
This is the test image.
![phone](https://github.com/showlab/DragAnything/assets/81640539/5bce2cff-ce61-49a9-919e-376987ba20a5)

**Comment by weijiawu** [comment]
You can provide a trajectory for background as well, with a fixed background and movement, for example, [[0,0],[0,0]...].

**Comment by syguan96** [comment]
Thanks! It works much better.
